// <auto-generated />
using System;
using LoghanAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoghanAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240206020518_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoghanAPI.Models.Logs.LogApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ApproveDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LaporanHarianId")
                        .HasColumnType("int");

                    b.Property<int>("StatusLaporanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("LaporanHarianId");

                    b.HasIndex("StatusLaporanId");

                    b.ToTable("LOG_ApprovalLaporan");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Application.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_Application");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Application.KategoriLaporan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_KategoriLaporan");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Kelompok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_Kelompoks");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.StatusPegawai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_StatusPegawai");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KelompokId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.ToTable("M_Units");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NPP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPegawaiId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusPegawaiId");

                    b.HasIndex("UnitId");

                    b.ToTable("M_Users");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Status.StatusLaporan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_StatusLaporan");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.AttachmentLaporan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LaporanHarianId")
                        .HasColumnType("int");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LaporanHarianId");

                    b.ToTable("TRX_AttachmentLaporan");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.LaporanHarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreaterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("KategoriLaporanId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreaterId");

                    b.HasIndex("KategoriLaporanId");

                    b.HasIndex("StatusId");

                    b.ToTable("TRX_LaporanHarian");
                });

            modelBuilder.Entity("LoghanAPI.Models.Logs.LogApproval", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.Main.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Transactions.LaporanHarian", "LaporanHarian")
                        .WithMany("LogApprovals")
                        .HasForeignKey("LaporanHarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Status.StatusLaporan", "StatusLaporan")
                        .WithMany("LogApprovals")
                        .HasForeignKey("StatusLaporanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("LaporanHarian");

                    b.Navigation("StatusLaporan");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Unit", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.Main.Kelompok", "Kelompok")
                        .WithMany("Units")
                        .HasForeignKey("KelompokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelompok");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.User", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.Main.StatusPegawai", "StatusPegawai")
                        .WithMany("User")
                        .HasForeignKey("StatusPegawaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Main.Unit", "Unit")
                        .WithMany("Users")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusPegawai");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.AttachmentLaporan", b =>
                {
                    b.HasOne("LoghanAPI.Models.Transactions.LaporanHarian", "LaporanHarian")
                        .WithMany("AttachmentLaporans")
                        .HasForeignKey("LaporanHarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaporanHarian");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.LaporanHarian", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.Application.Application", "Application")
                        .WithMany("LaporanHarians")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Main.User", "Creater")
                        .WithMany()
                        .HasForeignKey("CreaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Application.KategoriLaporan", "KategoriLaporan")
                        .WithMany("LaporanHarians")
                        .HasForeignKey("KategoriLaporanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Status.StatusLaporan", "Status")
                        .WithMany("LaporanHarians")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Creater");

                    b.Navigation("KategoriLaporan");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Application.Application", b =>
                {
                    b.Navigation("LaporanHarians");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Application.KategoriLaporan", b =>
                {
                    b.Navigation("LaporanHarians");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Kelompok", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.StatusPegawai", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Unit", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Status.StatusLaporan", b =>
                {
                    b.Navigation("LaporanHarians");

                    b.Navigation("LogApprovals");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.LaporanHarian", b =>
                {
                    b.Navigation("AttachmentLaporans");

                    b.Navigation("LogApprovals");
                });
#pragma warning restore 612, 618
        }
    }
}
