// <auto-generated />
using System;
using LoghanAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoghanAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoghanAPI.Models.Logs.LogApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ApproveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverNPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LaporanHarianId")
                        .HasColumnType("int");

                    b.Property<int>("StatusLaporanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LaporanHarianId");

                    b.HasIndex("StatusLaporanId");

                    b.ToTable("LOG_ApprovalLaporan", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Application.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_Application", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Application.KategoriLaporan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_KategoriLaporan", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Kelompok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_Kelompoks", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.StatusPegawai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_StatusPegawai", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KelompokId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.ToTable("M_Units", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JabatanId")
                        .HasColumnType("int");

                    b.Property<string>("NPP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusPegawaiId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("JabatanId");

                    b.HasIndex("StatusPegawaiId");

                    b.HasIndex("UnitId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("M_Users", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Status.StatusLaporan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_StatusLaporan", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.UserManagement.Jabatan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_Jabatan", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.UserManagement.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("M_Role", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.UserManagement.UserRole", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Username", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("M_UserRole", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.AttachmentLaporan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LaporanHarianId")
                        .HasColumnType("int");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LaporanHarianId");

                    b.ToTable("TRX_AttachmentLaporan", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.LaporanHarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreaterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("KategoriLaporanId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreaterId");

                    b.HasIndex("KategoriLaporanId");

                    b.HasIndex("StatusId");

                    b.ToTable("TRX_LaporanHarian", (string)null);
                });

            modelBuilder.Entity("LoghanAPI.Models.Logs.LogApproval", b =>
                {
                    b.HasOne("LoghanAPI.Models.Transactions.LaporanHarian", "LaporanHarian")
                        .WithMany()
                        .HasForeignKey("LaporanHarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Status.StatusLaporan", "StatusLaporan")
                        .WithMany()
                        .HasForeignKey("StatusLaporanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaporanHarian");

                    b.Navigation("StatusLaporan");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.Unit", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.Main.Kelompok", "Kelompok")
                        .WithMany()
                        .HasForeignKey("KelompokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelompok");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.User", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.UserManagement.Jabatan", "Jabatan")
                        .WithMany()
                        .HasForeignKey("JabatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Main.StatusPegawai", "StatusPegawai")
                        .WithMany()
                        .HasForeignKey("StatusPegawaiId");

                    b.HasOne("LoghanAPI.Models.Masters.Main.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Jabatan");

                    b.Navigation("StatusPegawai");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.UserManagement.UserRole", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.UserManagement.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Main.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.AttachmentLaporan", b =>
                {
                    b.HasOne("LoghanAPI.Models.Transactions.LaporanHarian", "LaporanHarian")
                        .WithMany()
                        .HasForeignKey("LaporanHarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaporanHarian");
                });

            modelBuilder.Entity("LoghanAPI.Models.Transactions.LaporanHarian", b =>
                {
                    b.HasOne("LoghanAPI.Models.Masters.Application.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Main.User", "Creater")
                        .WithMany()
                        .HasForeignKey("CreaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Application.KategoriLaporan", "KategoriLaporan")
                        .WithMany()
                        .HasForeignKey("KategoriLaporanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoghanAPI.Models.Masters.Status.StatusLaporan", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Creater");

                    b.Navigation("KategoriLaporan");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.Main.User", b =>
                {
                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("LoghanAPI.Models.Masters.UserManagement.Role", b =>
                {
                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
